version: "3.8"
services:
    srs:
        image: 76527413/srs:h265
        environment:
            - CANDIDATE=*
        ports:
            - 1935:1935
            - 8080:8080
            - 1985:1985
            - 8000:8000/udp
    ffmpeg-265:
        image: 76527413/ffmpeg:amd64
        volumes:
            - ./test.mp4:/test.mp4
        command: ffmpeg -y -re -stream_loop -1 -i test.mp4 -c:a copy -c:v libx265 -f flv rtmp://srs/live/h265
        depends_on:
            - srs
    ffmpeg-h264:
        image: 76527413/ffmpeg:amd64
        volumes:
            - ./test.mp4:/test.mp4
        command: ffmpeg -y -re -stream_loop -1 -i test.mp4 -c:a copy -c:v copy -f flv rtmp://srs/live/h264
        depends_on:
            - srs
    nginx:
        image: nginx:1.21.0
        ports:
            - 80:80
        volumes:
            - ./html:/usr/share/nginx/html
