#https://github.com/tsingsee/EasyPlayer.js http://127.0.0.1:8080/live/h265.flv
#https://github.com/ksvc/h265webplayer 
version: "3.8"
services:
    srs:
        image: 76527413/srs:h265
        environment:
            - CANDIDATE=*
        ports:
            - 1935:1935
            # - 8080:8080
            - 1985:1985
            - 8000:8000/udp
    ffmpeg-h264:
        image: 76527413/ffmpeg:amd64
        volumes:
            - ./h264.mp4:/test.mp4
        command: ffmpeg -y -re -stream_loop -1 -i test.mp4 -c:a copy -c:v copy -f flv rtmp://srs/live/h264
        depends_on:
            - srs
    ffmpeg-265: 
        image: 76527413/ffmpeg:amd64
        volumes:
            - ./h265.mp4:/test.mp4
        command: ffmpeg -y -re -stream_loop -1 -i test.mp4 -c:a copy -c:v copy -f flv rtmp://srs/live/h265
        depends_on:
            - srs
    nginx:
        image: nginx:1.21.0
        ports:
            - 8443:443
        volumes:
            - ./nginx/conf.d:/etc/nginx/conf.d
            - ./html:/usr/share/nginx/html
